### ISSUE TITLE
Determine input and output of weather API

### ISSUE THREAD

**Issue by shahshaan** [ClairvoyantChameleon/Run-Planner#13]

**Comment by chrisgrovers** [comment]
For input, we have a few options: 
Since we are currently working with just the current date at the beginning, all we need is current weather in a certain area for one location.
  http://openweathermap.org/current
  options are: city name, geographic coordinates, or zip code.

outputs from api are:
    wind (jacket)
    sunrise, sunset
    sky conditions(clouds)(hat/sunglasses)
    temp min, temp max (how warm to dress)
    humidity
    rain (rain apparel)

All conditions will actually help determine our recommended clothing

**Comment by chrisgrovers** [comment]
ex: 

api.openweathermap.org/data/2.5/weather?zip=94103,us

gives us: 

{
    "coord": {
        "lon": -122.41,
        "lat": 37.77
    },
    "sys": {
        "message": 2.1798,
        "country": "US",
        "sunrise": 1432817443,
        "sunset": 1432869796
    },
    "weather": [
        {
            "id": 800,
            "main": "Clear",
            "description": "sky is clear",
            "icon": "02d"
        }
    ],
    "base": "stations",
    "main": {
        "temp": 290.255,
        "temp_min": 290.255,
        "temp_max": 290.255,
        "pressure": 1020.24,
        "sea_level": 1028.37,
        "grnd_level": 1020.24,
        "humidity": 73
    },
    "wind": {
        "speed": 3.36,
        "deg": 242.501
    },
    "clouds": {
        "all": 8
    },
    "dt": 1432855515,
    "id": 0,
    "name": "San Francisco",
    "cod": 200
}
